server:
  port: ${SERVER_PORT:9091}

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.13:5432/website_application
    username: postgres
    password: smartcode
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  internal:
    key: ${INTERNAL_API_KEY:dev-key}